version: "3.7"

services:
  web-server:
    build:
      dockerfile: php.Dockerfile
      context: .
    restart: always
    volumes:
      - "./html/:/var/www/html/"
    ports:
      - "8080:80"

  mysql-server:
    image: mysql:8.0.22
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 13131
    volumes:
      - "./mysqldata/:/var/lib/mysql"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.4
    restart: always
    environment:
      PMA_HOST: mysql-server
      PMA_USER: root
      PMA_PASSWORD: 13131
    ports:
      - "5000:80"

# volumes:
#   mysql-data:
